version: '3'
services:
  nginx:
    build: ./nginx
    container_name: nginx_c
    ports:
      - 80:80
      - 443:443
    networks:
      custom_net:
        aliases:
          - rects.me
          - rects-en.me

    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./nginx/ssl:/etc/nginx/ssl

  php:
    build: ./php
    container_name: php_c
    volumes:
      - ../:/var/www
      - ./php/conf:/etc/php7
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    ports:
      - 9501:9501
    networks:
      - custom_net

  lucee:
    build:
      context: ./lucee
      args:
        LUCEE_VERSION: "5.3.7.48-RC"
        LUCEE_ADMIN_PASSWORD: "admin"
        LUCEE_EXTENSIONS: "6E2CB28F-98FB-4B51-B6BE6C64ADF35473"
        LUCEE_EXTENSIONS: "671B01B8-B3B3-42B9-AC055A356BED5281"
    container_name: lucee_c
    volumes:
      - ~/lucee/pmhs-lucee:/srv/www/webapps
      - ~/lucee/admin-lucee:/srv/www/webapps/ROOT
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    ports:
      - 8080:8080
    networks:
      - custom_net

  postgres:
    image: postgres
    restart: always
    container_name: postgres_c
    environment:
      POSTGRES_PASSWORD: admin
    networks:
      - custom_net

  adminer:
    image: adminer:latest
    restart: always
    container_name: adminer_c
    ports:
      - 8181:8080
    networks:
      - custom_net


  # mysql:
    # image: jbergstroem/mariadb-alpine
    # container_name: mysql_c
    # environment:
      # MYSQL_ROOT_PASSWORD: root
    # ports:
      # - 3306:3306
    # networks:
      # - custom_net
    # volumes:
      # - ./mariadb:/var/lib/mysql
    # restart: always

  mysql:
    build: ./mysql
    container_name: mysql_c
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    networks:
      - custom_net
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always

  redis:
    # build: ./redis
    image: redis:5-alpine
    container_name: redis_c
    ports:
      - 6379:6379
    networks:
      - custom_net
    volumes:
      - ./redis/data:/data
    restart: always

  # mongodb:
    # build: ./mongodb
    # container_name: mongodb_c
    # ports:
      # - 27017:27017
    # networks:
      # - custom_net
    # volumes:
      # - ./mongodb/data:/data/db
    # restart: always

networks:
  custom_net:
   external:
      name: app_net
