version: '3'
services:
  nginx:
    build: ./nginx
    container_name: nginx_c
    ports:
      - 80:80
      - 443:443
    networks:
      custom_net:
        aliases:
          - rects.me

    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./nginx/ssl:/etc/nginx/ssl

  php:
    build: ./php
    container_name: php_c
    volumes:
      - ../:/var/www
      - ./php/conf:/etc/php7
    ports:
      - 9501:9501
    networks:
      - custom_net
  mysql:
    build: ./mysql
    container_name: mysql_c
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    networks:
      - custom_net
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
  redis:
    build: ./redis
    container_name: redis_c
    ports:
      - 6379:6379
    networks:
      - custom_net
    volumes:
      - ./redis/data:/data
    restart: always
  mongodb:
    build: ./mongodb
    container_name: mongodb_c
    ports:
      - 27017:27017
    networks:
      - custom_net
    volumes:
      - ./mongodb/data:/data/db
    restart: always

networks:
  custom_net:
   external:
      name: app_net
